# Generated by Django 6.0.3 on 2026-08-15 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                ("delete_sequences", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("lastchanged", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name for this sequence.",
                        max_length=255,
                        unique=True,
                        verbose_name="Sequence Name",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "can_resend_sequence",
                    models.BooleanField(
                        default=False,
                        help_text="This will allow you to resend emails to users with the same Sequence when query matches the user again.",
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(blank=True, help_text="Set a custom from email.", max_length=254, null=True),
                ),
                (
                    "from_email_name",
                    models.CharField(
                        blank=True, help_text="Set a name for a custom from email.", max_length=150, null=True
                    ),
                ),
                ("subject_template", models.TextField(blank=True, null=True)),
                (
                    "body_html_template",
                    models.TextField(
                        blank=True, help_text="You will have settings and user in the context.", null=True
                    ),
                ),
                ("message_class", models.CharField(blank=True, default="default", max_length=120)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="If set, this is the campaign to which this Sequence belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="email_sequences.campaign",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SentEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("subject", models.TextField()),
                ("body", models.TextField()),
                ("from_email", models.EmailField(default=None, max_length=254, null=True)),
                ("from_email_name", models.CharField(default=None, max_length=150, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_emails",
                        to="email_sequences.sequence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuerySetRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("lastchanged", models.DateTimeField(auto_now=True)),
                (
                    "method_type",
                    models.CharField(
                        choices=[("filter", "Filter"), ("exclude", "Exclude")], default="filter", max_length=12
                    ),
                ),
                ("field_name", models.CharField(max_length=128, verbose_name="Field name of User")),
                (
                    "lookup_type",
                    models.CharField(
                        choices=[
                            ("exact", "exactly"),
                            ("iexact", "exactly (case insensitive)"),
                            ("contains", "contains"),
                            ("icontains", "contains (case insensitive)"),
                            ("regex", "regex"),
                            ("iregex", "regex (case insensitive)"),
                            ("gt", "greater than"),
                            ("gte", "greater than or equal to"),
                            ("lt", "less than"),
                            ("lte", "less than or equal to"),
                            ("startswith", "starts with"),
                            ("endswith", "ends with"),
                            ("istartswith", "starts with (case insensitive)"),
                            ("iendswith", "ends with (case insensitive)"),
                        ],
                        default="exact",
                        max_length=12,
                    ),
                ),
                ("rule_type", models.CharField(choices=[("or", "Or"), ("and", "And")], default="and", max_length=3)),
                (
                    "field_value",
                    models.CharField(
                        help_text="Can be anything from a number, to a string. Or, do `now-7 days` or `today+3 days` for fancy timedelta.",
                        max_length=255,
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queryset_rules",
                        to="email_sequences.sequence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserUnsubscribe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_unsubscribes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserUnsubscribeCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_unsubscribe_campaigns",
                        to="email_sequences.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_unsubscribe_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="unsubscribed_users",
            field=models.ManyToManyField(
                related_name="campaign_unsubscribed_users",
                through="email_sequences.UserUnsubscribeCampaign",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserUnsubscribeSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_unsubscribe_sequences",
                        to="email_sequences.sequence",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_unsubscribe_sequences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sequence",
            name="unsubscribed_users",
            field=models.ManyToManyField(
                related_name="sequences_unsubscribed",
                through="email_sequences.UserUnsubscribeSequence",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
